<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>storychief-xperience-example</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kentico.Xperience.Admin" />
    <PackageReference Include="Kentico.Xperience.AzureStorage" />
    <PackageReference Include="Kentico.Xperience.ImageProcessing" />
    <PackageReference Include="Kentico.Xperience.WebApp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/StoryChief.Xperience/StoryChief.Xperience.csproj" />
  </ItemGroup>

</Project>
